### ISSUE TITLE
Share NotePads across accounts.

### ISSUE THREAD

**Issue by ElSenor64** [MicroPad/Web#130]
I really like the ability to export/import notebooks, and especially love the ability to export as PDF since it lets me turn in my notes to my teachers.

But what if I'm keeping a to do list for my robotics team in MicroPad, and multiple people need to access it? The best Idea I could come up with was to create one MicroSync account and give everyone the credentials, but this is annoying for everyone and having to log in and out of my personal account to access it has grown wearisome. Please make it so there's a sharing function between MicroSync accounts.

I love your app so much! Thank you!

**Comment by NickGeek** [comment]
Thanks for the feedback! I could make it so multiple accounts have access to a notepad but without further work that could potentially create issues if two users were editing the notepad at the same time.

I definitely want to get notebook collaboration working, although it won't be an easy task. If you have any feedback on how you think I should implement this, I'd love to hear it.

One slightly hacky way to do this (outside of MicroSync) might be to export the notebook into a shared Google Drive/Dropbox folder using Ctrl/Cmd+S and then getting your classmates to import from that file every time they open the notebook. I realise that isn't ideal and I really want to get collaboration working too.

**Comment by ElSenor64** [comment]
Thanks!

**Comment by NickGeek** [comment]
@ElSenor64 As of MicroPad v3.17.1 there is collaboration for notepads via MicroSync.
