### ISSUE TITLE
Show PDFs in notes

### ISSUE THREAD

**Issue by kosmynin** [MicroPad/Web#137]
Very nice app, but it would be nice to be able to insert PDFs so that you can view and comment on them in the notebook page (as you can do in e.g. OneNote (maybe by converting them to images and inserting them?)).

**Comment by NickGeek** [comment]
https://pdfobject.com might be a promising way to implement this. However, images might be nicer for taking notes alongside.

I might end up supporting both implementations like so:
- Add a new PDF element type, which shows a scrollable PDF viewer as an element (that would be a new element type with parser support)
- Add a MicroPad client specific feature to upload a PDF and turn those into image elements
- Add both of those options to the insert menu
