### ISSUE TITLE
[Question] Connections between notes

### ISSUE THREAD

**Issue by ehhc** [MicroPad/Web#148]
Hey guys,
i just found your project and it seems quite cool.
But i have one question: is it possible to "connect" notes? 
Can i create networks of notes? where one note is connected with another etc.?

**Comment by NickGeek** [comment]
You can put your notes in a section, so they'll all be grouped under that.

You can also use hashtags. So anywhere in a text element in your note, just put a hashtag like #project or something and then when you search for #project (or click on the tag) it'll show you all your notes across all of your notebooks with that hashtag in them.

I use a #todo hashtag in all of my notes with active todo lists to connect them together.

**Comment by ehhc** [comment]
Thanks for your answer. I fear thats not what i meant, resp. what i was looking for, but you've answered the question nontheless. Thanks again :)

**Comment by coldwinds** [comment]
@NickGeek I think what @ehhc mean is connected not grouped, it's a graph relationship not hierarchical relationship(namely grouped) of note blocks / notes. Lots of things in the human mind are connected with each other, it's not like a tree. So when we write our mind as notes it should be connect-able with each other that would be a great help for us to mange things.

Please refer this video for a visual example :)

https://www.youtube.com/watch?v=GFqLUBKCFdA

**Comment by NickGeek** [comment]
@coldwinds I see, it's a directed graph of elements. I'm not quite sure how to fit that into the current model in MicroPad, although I am open to suggestions.

If a non-directed, non-disjoint graph works, then hashtags can be used to achieve that, but that's obviously less structured than what you're proposing.

**Comment by coldwinds** [comment]
> @coldwinds I see, it's a directed graph of elements. I'm not quite sure how to fit that into the current model in MicroPad, although I am open to suggestions.
> 
> If a non-directed, non-disjoint graph works, then hashtags can be used to achieve that, but that's obviously less structured than what you're proposing.

Hello, I think the wiki links between each other have constructed a graph of links, it just not visualized, I'm ok with that, The user just use list of wiki links instead of tree list can fulfill this demand. The problem is, if user change the name of wiki link, the link text could not change in sync with the other wiki page that reference this link easily.

**Comment by NickGeek** [comment]
@coldwinds yes, changing the name of one does present a challenge. A possibly hacky solution is to open the NPX file in a text editor and find/replace all instances.

**Comment by ehhc** [comment]
Hey guys, just wanted to let you know that i found a tool seeming to fulfill my need of connected notes (alas, closed source :( ). It's called https://obsidian.md/ 
Hope it's okay to post that here; i don't want to advertise a foreign tool, but maybe somebody is looking for the same as i did and finds the mentioned tool helpful.
Besides that, if it would be possible to do something similar using you cool open source tool, that would be awesome
