### ISSUE TITLE
Elements moved past the top of the display can't easily be retrieved

### ISSUE THREAD

**Issue by corypanshin** [MicroPad/Web#156]
If I grab a card by its handle and move it up until the handle disappears off the top of the display area, there seems to be no way to get it back down.  This happens both in edit mode and when the card is closed.  If the entire note has previously been scrolled down somewhat, scrolling up again will bring the card back into view.  But otherwise the only solution I've found is to close and reopen the program, at which point the card reappears slightly belong the top of the display.

Windows 7.  Desktop version.

**Smartphone (please complete the following information):**

**Additional context**

**Comment by NickGeek** [comment]
Hey, sorry about that! You don't actually need to close/reopen the whole program, if you just open another note and then go back to it, it'll be fixed up. It is definitely a good idea to make it so you can't be in that position though, I'll add that to the list :-)
