### ISSUE TITLE
Markdown Import

### ISSUE THREAD

**Issue by NickGeek** [MicroPad/Web#157]
**Is your feature request related to a problem? Please describe.**
It's the client implementation of this request: https://github.com/MicroPad/Web-Parser/issues/13

**Describe the solution you'd like**
You should be able to select a bunch of markdown files and then MicroPad should call the new functions in the parser (https://getmicropad.com/docs/upad-parse/modules/_translators_.translators.markdown.html) to make a notepad from them.

**Comment by NickGeek** [comment]
@rustyraptor was the original requester

**Comment by RustyRaptor** [comment]
Nice
