### ISSUE TITLE
New note should open under the mouse

### ISSUE THREAD

**Issue by yuxiliu1995** [MicroPad/Web#165]
**Is your feature request related to a problem? Please describe.**
Pressing "n" opens a new note at the top left corner, which I must then manually drag to the right position. This is particularly frustrating when the canvas is big.

**Describe the solution you'd like**
Pressing "n" opens the new note right under the mouse.

**Comment by NickGeek** [comment]
I'd love this too, but the browser won't reveal mouse location, so it can't actually be implemented.
