### ISSUE TITLE
Username/password lose focus on Mac (Safari)

### ISSUE THREAD

**Issue by printfn** [MicroPad/Web#179]
**Describe the bug**
When I try logging in to µSync in Safari on Mac, the username/password input fields seem to lose focus when releasing the mouse button. This makes it impossible to type in a username/password, but using a password manager still works. The same issue also exists on iOS, but not in Chrome on Mac.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to https://web.getmicropad.com/
2. Click on Notebooks -> Connect to µSync
3. Scroll down to 'Username' and click on the textbox
4. Textbox loses focus as soon as the mouse button is released.

**Expected behaviour**
Textbok remains focussed so I can type in it.

**Screenshots**
<img width="674" alt="image" src="https://user-images.githubusercontent.com/1643883/63525210-98bffe00-c4fd-11e9-8f25-b9e77c6f2e14.png">

**Desktop (please complete the following information):**
 - OS: macOS / iOS
 - Browser: Safari
 - Version: Safari 13.0 on macOS 10.15, or Mobile Safari on iOS 13

**Comment by NickGeek** [comment]
Thanks for the report!

I've managed to reproduce it. It seems to not happen the first time I click in, but it does all subsequent times.
