### ISSUE TITLE
Can't build and run latest on Windows 

### ISSUE THREAD

**Issue by 4asifm** [MicroPad/Web#202]
Description:
Followed the documentation
1. yarn
2. yarn start

Server starts fine, but when I navigate to http://localhost:3000 - it throws up

```
**Unhandled Rejection (TypeError): callback is not a function**
./src/react-web/index.tsx/</<
d:/dev_wksd/src-code/micropad-web/app/src/react-web/index.tsx:109

  106 | 	document.getElementById('app') as HTMLElement
  107 | );
  108 | 
> 109 | if (!await localforage.getItem('hasRunBefore')) store.dispatch(actions.getHelp.started());
  110 | await localforage.setItem('hasRunBefore', true);
  111 | 
  112 | await displayWhatsNew();


```
Windows - 7 Pro
Node - v10.16.3
yarn - 1.19.1

**Comment by NickGeek** [comment]
What web browser are you using?

**Comment by 4asifm** [comment]
Firefox : 71.0 (64-bit)
Chrome : Version 78.0.3904.108 (Official Build) (64-bit)

crashes in both.

**Comment by NickGeek** [comment]
Interesting. I'll get my hands on a Windows device and see what's up.

**Comment by 4asifm** [comment]
Happy to help with tests , log, etc. Please let me know

**Comment by NickGeek** [comment]
I just tried to replicate this on Windows 10 and it worked. I wonder if it's a Windows 7 issue?

I'd suggest wiping your `node_modules` and running `yarn` again.

**Comment by NickGeek** [comment]
Due to a lack of update I'm going to close this. If you're still running into problems please let me know @4asifm.
