### ISSUE TITLE
Searching by note name stopped working

### ISSUE THREAD

**Issue by s1mpl3-0n3** [MicroPad/Web#213]
**Describe the bug**
Searching by note name stopped working for both the web version and the desktop version.

On the desktop version the notes are visible, but cannot be selected, where on the web version the notes don't appear at all.

**To Reproduce on Desktop**
Steps to reproduce the behaviour:
1. Press CTRL+F
2. Type in a note name
3. Click on the note name
4. Nothing happens

**To Reproduce on Web**
Steps to reproduce the behaviour:
1. Press CTRL+F
2. Type in a note name
3. Nothing appears as a result

**Expected behaviour**
I should be able to search, find and open up notes using the app search feature. 

**Desktop:**
 - OS: Ubuntu 18
 - Micropad v3.21.0

**Web:**
 - OS: Ubuntu 18
 - Browser Google Chrome 
 - Version 80.0.3987.149 (Official Build) (64-bit)

**Comment by NickGeek** [comment]
What happens if you press the down arrow?

![latest](https://user-images.githubusercontent.com/3462055/78194654-3b038380-74da-11ea-9771-a534d5619e71.png)

**Comment by s1mpl3-0n3** [comment]
Yes, like that the options appear on both web and desktop, but I'm still unable to open the note itself by choosing one of the options.

**Comment by NickGeek** [comment]
Hmm, it seems to work for me. Would you mind sending me the notebook, or a smaller example one you get the bug on?

Also, does updating to 3.21.9 work at all?

**Comment by s1mpl3-0n3** [comment]
I just updated to 3.21.9, but it's still not working. 

I'll send you the notebook to your email.

**Comment by NickGeek** [comment]
Hi,
Thanks for sending me the notebook. I managed to track down the issue. There is an empty markdown element (`markdown9`) in a note titled "Annotation". That was being read as having contents of `undefined` (instead of empty string). This shouldn't actually be a possible state to be in, so I'll do some more digging later.

```
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<notepad xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="https://getmicropad.com/schema.xsd" title="Empty Content">
    <section title="Test section">
        <note title="Test note">
            <addons/>
            <bibliography/>
            <markdown id="markdown9" x="25px" y="2990px" width="auto" height="auto" fontSize="16px"/>
        </note>
    </section>
</notepad>
```

Is a minimal notebook that will replicate it.

This is fixed in https://github.com/MicroPad/Web/releases/tag/v3.21.10 by https://github.com/MicroPad/Notebook-Library/commit/0648bea73824ceb04cbe08918fbd5500606034e4.

Electron updates will go out after web finishes building.

**Comment by NickGeek** [comment]
(note: the fix is that a notebook in a bad state will be fixed upon being imported, that means that you will need to save (Ctrl+S/Cmd+S) and open (Ctrl+O/Cmd+O) the notebook for it to be fixed)

**Comment by s1mpl3-0n3** [comment]
Thank you for the quick reaction! I'll test it a bit later.
