### ISSUE TITLE
include triple back-tick in markdown help

### ISSUE THREAD

**Issue by reidwicks** [MicroPad/Web#68]
this information is missing, and it would be very helpful for users if it were included in the help section

**Comment by NickGeek** [comment]
In what situation would you use this feature? If you're talking about code blocks or something, simply wrap the block you don't want formatted with three \` symbols, like so:

\`\`\`  
not formatted as \*markdown\*
\`\`\`  

(becomes)

```
not formatted as *markdown*
```

**Comment by NickGeek** [comment]
Will do!
