### ISSUE TITLE
Colorful text

### ISSUE THREAD

**Issue by nablabits** [MicroPad/Web#73]
It would be pretty cool to have colorful text to visualize concepts

**Comment by nablabits** [comment]
This is --roughly-- what I mean, now i work it around by using graphics tablet and adding an image to the notepad aftewards.
![maclaurin series sinx (solid).png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5bd4b21ce97b300011e013aa/125516c66e82c728ace21e0d46e595992f8396bb86e7ff50a14ff9913a06347a271ce363638aef21bb0b394d4d1f0cf31b0d0c00eef39b2ef4b33a218e090febd1695672923d11adec821cec05b829995397f4edd4189fb5646fb2c99d452c1f0c1288fa5935a69f4dce5ef74ce04a47e9.png)

**Comment by NickGeek** [comment]
Thanks for the suggestion! Can I just ask if this is about drawing elements or the markdown/text elements?

**Comment by nablabits** [comment]
Right, at first I started to write a comment over there (on #65) but then i realized that they were about drawings rather than to text. 

![screenshot_2018-10-28_13-21-07](https://user-images.githubusercontent.com/33068707/47615869-9182bc00-dab5-11e8-9c13-50ea89d9fcd1.png)
Imagine this bunch of formulas with colourful text, the readability & understanding would be really improved. 

I've very little idea about react but if you want some help, say writing docs, just tell me, I'll try to make some time for it in exchange for this feature ;)

**Comment by NickGeek** [comment]
Oh awesome. I like your note there too 😊.

This should be pretty quick to do, I'm thinking about adding another extension to markdown to do something like this:
```
c[This is *my* ''2x^2 + 4'' mathy stuff in red](red) and this is c[amber](#ffb300).
```
for the syntax.

That mirrors how images and links work in markdown and should be fairly easy to parse. Do you think that would work for you?

**Comment by NickGeek** [comment]
Cool. That should be doable. I'm happy to add it to the help, but if you want to know how that works, it's the notebook in `app/src/assets/Help.npx`. There's a note with the markdown formatting guide in there, and that's what's used on that modal.

**Comment by NickGeek** [comment]
![colourful text](https://user-images.githubusercontent.com/3462055/47712692-3ad7d680-dc9d-11e8-8b24-c39c44a093cc.png)

I think I have it working.

**Comment by nablabits** [comment]
Great! I'm dealing right now with the help npx file

**Comment by NickGeek** [comment]
Cool. Colours are live in 3.12.0 right now, which is live at https://web.getmicropad.com. It will come to the electron apps soon. I currently have to manually package those up though.

**Comment by nablabits** [comment]
Fantastic! thanks a lot!
